selected_medium_image_background:string=#fff
metadata_bar_background:string=#f6f6f6
photographer_font_color:string=#000
title_font_color:string=#000
metadata_edit_label_color:string=#000
metadata_edit_panel_background:string=#ddd
metadata_panel_border_sep_color:string=#fff
metadata_input_font_color:string=#000
metadata_input_background:string=#f5f5f5
metadata_input_border_color:string=#d5d5d5
metadata_input_hover_background:string=#fafafa
metadata_input_focus_font_color:string=#000
metadata_input_focus_background:string=#fff
metadata_input_border_focus_color:string=#96b6d6
portfolio_slide_background:string=#555
portfolio_slide_hover_background:string=#606060
portfolio_slide_text_color:string=#000
slide_background:string=#e0e0e0
slide_hover_background:string=#ebebeb
slide_selected_background:string=#e6ecf2
filmbar_background:string=#fff
filmbar_displayed_img_background:string=#bfbfbf
filmbar_hover_img_background:string=#e8e8e8